export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const QUESTION_LOADING = "QUESTION_LOADING";
export const GET_QUESTION = "GET_QUESTION";
